# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Task": "00_core.ipynb",
         "WorkflowDefinition": "00_core.ipynb",
         "Config": "00_core.ipynb",
         "Workflow": "00_core.ipynb",
         "render": "02_graph.ipynb",
         "load": "02_graph.ipynb",
         "build_workflow": "02_graph.ipynb",
         "build_graph": "02_graph.ipynb",
         "load_definition": "02_graph.ipynb",
         "load_configuration": "02_graph.ipynb",
         "workflow_definition": "02_graph.ipynb",
         "workflow_configuration": "02_graph.ipynb",
         "build": "02_graph.ipynb",
         "templater": "02_graph.ipynb",
         "Templater": "04_adapters.ipynb",
         "JinjaTemplater": "04_adapters.ipynb"}

modules = ["domain/model.py",
           "services/all.py",
           "adapters/templater.py"]

doc_url = "https://candle-stick.github.io/flow/"

git_url = "https://github.com/candle-stick/flow/tree/master/"

def custom_doc_links(name): return None
