task_types:
    ssh:
        operator:
            SSHOperator:
                ssh_hook: SSHHook(ssh_conn_id=dev_config["emr_con_id"])
                command: "'some command'"
                timeout: 30
                retries: 3
                retry_delay: timedelta(seconds=45)
        imports:
            airflow.contrib.operators.ssh_operator: [SSHOperator]
            airflow.contrib.hooks: [SSHHook]
            
    bash:
        operator:
            BashOperator:
                bash_command: sleep
                retries: 3
        imports:
            airflow.operators.bash_operator: [BashOperator]

    subtask:
        operator:
            SubDagOperator:
                retries: 3
        imports:
            airflow.operators.subdag_operator: [SubDagOperator]