###########################################################################################
# Conventions
# -----
# Names: unique, lowercase, and separated by underscores
# 
# Dependencies
# ------------
# Upstream dependencies of task
#
# Type
# ----
# Task type. One of `ssh` and `subtask`. Will be mapped to pre-configured Airflow operator.
#   - ssh 
#         default type used to submit jobs to Amazon EMR cluster.
#   - subtask 
#         references a subworkflow or subdag. The name of a task with type `subtask` must
#         match a subtask defined in the `subtasks` section.
###########################################################################################

name: example-dag

default_args:
    owner: "'airflow'" 
    depends_on_past: False
    start_date: datetime(2018, 5, 26)
    retries: 1
    retry_delay: timedelta(minutes=5)
    
dag_args:
    description: "'An example DAG'"
    schedule_interval: "'@daily'"

tasks:
    task1:
      dependencies: []
      type: ssh
      parameters:
        retries: 4
        
    task2:
      dependencies: [task1]
      type: ssh
      parameters: 
        retries: 4 
        
    task3:
      dependencies: [task2]
      type: ssh
      parameters:
        retries: 3
        
    snapshot_entity:
        dependencies: [task3]
        type: subtask
        parameters: {}
        
subtasks:
    snapshot_entity:
        task1:
          dependencies: []
          type: ssh
          parameters:
            retries: 3

        task2:
          dependencies: [task1]
          type: ssh
          parameters: 
            retries: 3 

    delta_entity:
        task1:
          dependencies: []
          type: ssh
          parameters:
            retries: 3

        task2:
          dependencies: [task1]
          type: ssh
          parameters: 
            retries: 3 